# Introduction to Computer Programming and Numerical Methods

> **Mohamad M. Hallal, PhD** <br> Teaching Professor, UC Berkeley

[![License](https://img.shields.io/badge/license-CC%20BY--NC--ND%204.0-blue)](https://creativecommons.org/licenses/by-nc-nd/4.0/)
***

# NumPy Arrays 

1. [**Introduction to NumPy Arrays**](#s1)
2. [**Indexing Arrays**](#s2)
3. [**Manipulating Arrays**](#s3)
4. [**Array Methods**](#s4)
5. [**Arithmetic and Comparison Operations**](#s5)

***

# 0. Motivation

While Python's built-in data structures like lists and tuples are versatile, they may not always provide the performance and efficiency required for complex numerical computations, especially when dealing with large datasets or multidimensional arrays. This is where NumPy comes into play. NumPy, short for "Numerical Python", is one of the most used modules for scientific and numerical applications. NumPy is a large and extensive module, and this section is just a brief introduction. In addition to performance benefits, NumPy provides a wide range of mathematical functions for array manipulation, linear algebra, and more. These functions are optimized for efficiency and are essential for various scientific and engineering applications.

**Learning objectives:**

* Create 1-D and 2-D arrays using different methods
* Access individual elements and slices of arrays using indexing and slicing techniques
* Modify elements and slices of arrays
* Perform arithmetic and comparison operations on arrays
* Use advanced indexing methods like boolean indexing to access and modify array elements

# 1. Introduction to NumPy Arrays <a id="s1"></a>

To utilize NumPy, it must first be imported.  A conventional way to import it is to use `np` as a shortened name: `import numpy as np`

<div class="alert alert-block alert-warning"> <b>NOTE!</b> While you could use any name, <code>np</code> is widely accepted by the community and it is a good practice to use it for consistency and readability.</div>

## 1.1. 1-D Array (or Vector)

The main data structure in NumPy is the `ndarray`, which stands for N-dimensional array. When working with NumPy, an `ndarray` is simply referred to as an array. It contains data of the same type, such as integers or floating-point values. 

To define an array in Python, you can use the `np.array()` function. This function takes as input a list `[]` or a tuple `()` and converts it to a NumPy array. You can also provide an argument of type `range` to `np.array()`. So, the items are put inside square brackets `np.array([...])` or a second set of parentheses `np.array((...))`, and are separated by commas `,`.

**Examples:**

```python
>>> array1 = np.array([1, 2, 3, 4])   # Using a list
>>> array2 = np.array((1, 2, 3, 4))   # Using a tuple
>>> array3 = np.array(range(1, 5))    # Using a range
```

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Create the following array in NumPy and then check its type using <code>type()</code>: <br> <br> $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$ <br></div> 

In [1]:
import numpy as np
x = np.array((-2, 4, 3, 12))
type(x)

numpy.ndarray

## 1.2. 2-D Array (or Matrix)

The above variable `x` is a 1-D array, also known as a vector. We can also define a 2-D array, also known as a matrix. A 2-D array is essentially a collection of 1-D arrays (rows), stacked one after another. To define a 2-D array, you use `np.array()` with a list of lists, where each row is a list: `np.array([[row1], [row2], ...])` or a tuple of tuples, where each row is a tuple: `np.array(((row1), (row2), ...))`. The items within each row are separated by commas `,`, and the lists or tuples that enclose each row are also separated by commas `,`.

**Examples:**

```python
>>> array1 = np.array([[1, 2, 3], [4, 5, 6]])   # Using nested lists
>>> array2 = np.array(((1, 2, 3), (4, 5, 6)))   # Using nested tuples
```

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Create the following array and then check its type using <code>type()</code>: <br> <br> $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ <br></div> 

In [57]:
y = np.array(((1, 4, 3), (9, 2, 7)))

type(y)

numpy.ndarray

## 1.3. Array Attributes

In NumPy, arrays have attributes that provide useful information about their shape, size, and dimensionality. These attributes help you understand the structure of the array and perform operations accordingly. Here are some of the common attributes:
* [`array_name.shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html): returns the shape of `array_name`
> returns a `tuple` with `(n_rows, n_columns)`, where the first element is the number of rows and the second element is the number of columns in the array

* [`array_name.size`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html#numpy.ndarray.size): returns the total number of elements in `array_name` 
> this is the number of rows times number of columns
* [`array_name.ndim`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html#numpy.ndarray.ndim): returns the number of dimensions of `array_name`
> this indicates whether the array is 1-D, 2-D. etc.

These are just a few of the attributes available for NumPy arrays. For a complete list, you can refer to the [official documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

<br>

<center><figure>
  <img src="https://docs.google.com/drawings/d/1vNr9OCNVuha4NLtoAi7udvnXe9mO-Lyhd9aBglaaz94/pub?w=1440&h=1080" style="width:50%">
    <figcaption style="text-align:center"><strong> <br> NumPy array attributes</strong></figcaption>   
</figure></center>

<br>

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Get the dimension, shape, and size of array <code>y</code>.</div> 

In [5]:
y.ndim

2

In [7]:
y.shape

(2, 3)

In [9]:
y.size

6

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Notice that we used <code>y.shape</code> instead of <code>y.shape()</code>. This is because <code>shape</code> is an <strong>attribute</strong>, which is a value associated with an object. For now you need to remember that when we call an attribute on an object, we do not use parentheses. You can always try both and see which works!</div>

## 1.4. Other Ways for Creating Arrays

In addition to `np.array()`, NumPy provides several functions for creating arrays with specific patterns or sequences. For instance, if we want to create the array `z = [1, 2, 3, ..., 365]`, it would be very cumbersome to manually type each value from 1 through 365. Below, we introduce several functions for efficiently creating arrays that have a pattern.

|           | `np.arange()`                                  | `np.linspace()`                                            |
|:----------|:-----------------------------------------------|:-----------------------------------------------------------|
| **Generates** | Evenly spaced values within a specified range  | Evenly spaced values within a specified range          |
| **Arguments** | `start`: Start value (optional, default 0)     | `start`: Start value (required)                        |
|           | `stop`: End value (required)                   | `stop`: End value (required)                               |
|           | `step`: Increment (optional, default 1)        | `num`: Number of values to generate (optional, default 50) |
| **End Value** | Exclusive                                    | Inclusive                                                |

### 1.4.1. `np.arange()`

For creating arrays with **evenly spaced values** within a specific range, where you know the increment between the values, it is useful to use the `np.arange()` function:

```python
np.arange(start, stop, step)
```

where:

* `start`: a number specifying the start value of the array. This is an optional argument. If not specified, it defaults to 0.
* `stop`: a number specifying the end value of the array (exclusive). This is a required argument.
* `step`: a number specifying the increment in the values of the array (`step` $\neq 0$). This is an optional argument. If not specified, it defaults to 1. The `step` can be positive or negative and the value in index `i` will simply be `start + step*i`

The resulting array will include values from `start` up to, **but not including**, `stop`, with a spacing of `step` between each two values.

<div class="alert alert-block alert-warning"> <b>NOTE!</b> This should sound familiar. We have seen the <code>range()</code> function before. However, <code>range()</code> is used for integer sequences only, while <code>np.arange()</code> can take non-integer values as well. For integer arguments, the functions are roughly equivalent.</div>

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Create an array with $[0.5, 1.0, 1.5, 2.0, ..., 6.0, 6.5]$. <br> &emsp;&emsp;&emsp;&ensp; Create an array with $[0, 1, 2, ..., 6]$.</div> 

In [21]:
np.arange(0.5, 7, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Run the code below and change the values for start, stop, and step to check how they affect the array.</div> 

In [23]:
import ipywidgets as widgets  # import ipywidgets package for interactive widgets

# create 3 sliders for start, stop, and step
@widgets.interact(start=(-100, 100), stop=(-100, 100), step=(-5, 10, 0.5))

# define a function that takes the values from the sliders and returns the ndarray
def arange(start, stop, step):
    print(f'\n >>> np.arange(start={start}, stop={stop}, step={step:.2f}) \n')
    print(np.arange(start, stop, step))
    return

interactive(children=(IntSlider(value=0, description='start', min=-100), IntSlider(value=0, description='stop'…

### 1.4.2. `np.linspace()`

For creating arrays with **evenly spaced values** within a specific range, where you know the total number of values, it is useful to use the `np.linspace()` function:

```python
np.linspace(start, stop, num)
```

where:

* `start`: a number specifying the start value of the array. Here, this is a required argument.
* `stop`: a number specifying the end value of the array (inclusive). This is a required argument.
* `num`: an integer specifying the number of evenly spaced points to generate between `start` and `stop`, including `start` and `stop`. This is an optional argument. If not specified, it defaults to 50.

The resulting array will include `num` values between `start` and `stop`, inclusive of both endpoints.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Create an array starting at 3, ending at 9, and containing 10 evenly spaced elements.</div> 

In [86]:
np.linspace(3, 9, 7)

array([3., 4., 5., 6., 7., 8., 9.])

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Run the code below and change the values for start, stop, and num to check how they affect the array.</div> 

In [27]:
import ipywidgets as widgets  # import ipywidgets package for interactive widgets

# create 3 sliders for start, stop, and step
@widgets.interact(start=(-100, 100), stop=(-100, 100), num=(0, 100))

# define a function that takes the values from the sliders and returns the ndarray
def linspace(start, stop, num):
    print(f'\n >>> np.linspace(start={start}, stop={stop}, num={num}) \n')
    print(np.linspace(start, stop, num))
    return

interactive(children=(IntSlider(value=0, description='start', min=-100), IntSlider(value=0, description='stop'…

### 1.4.3. Other Functions

In addition to `np.arange()` and `np.linspace()`, NumPy provides several other functions for creating predefined arrays, which can be highly useful in various numerical computations. Three commonly used functions are:

* `np.zeros(shape)`: Returns an array filled with zeros, with the specified shape.
* `np.ones(shape)`: Returns an array filled with ones, with the specified shape.
* `np.empty(shape)`: Returns an uninitialized array with the specified shape. The values in the array will be arbitrary and may vary.

All of these functions take an input argument `shape`, which specifies the shape of the array. This should be of type `tuple` with `(n_rows, n_columns)`. If you only need a 1-D array, you can specify just one number instead of both the number of rows and number of columns.

<div class="alert alert-block alert-warning"> <b>NOTE!</b> When calling these functions to create 2-D arrays, make sure to include two sets of parentheses, one for the function itself and one for the <code>shape</code> argument: <code>np.zeros((n_rows, n_columns))</code>.</div>

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Create a 3 by 5 array with all the elements as 0. <br> &emsp;&emsp;&emsp;&ensp; Create a 1-D empty array with 10 elements.</div> 

In [29]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.empty(10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

<div class="alert alert-block alert-warning"> <b>NOTE!</b> The empty array is not really empty, it is filled with random numbers.</div>

There are other functions in NumPy for creating arrays. You can read about them in the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html).

## 1.5. Membership Operators

We can check whether a specific value is present in an array using the membership operators: `in` and `not in`.


```python
value in array_name
value not in array_name
```

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Check if 0 is in an empty array with 10 rows and 10 columns.</div> 

In [37]:
0 in np.empty((10, 10))

True

In [39]:
np.empty((10, 10))

array([[4.94065646e-324, 6.95230721e-310, 3.77960219e-321,
                    nan, 4.94065646e-322, 3.74168656e+233,
        5.26520936e+170, 1.16226599e-012, 7.75110943e+228,
        4.52338016e+257],
       [2.65497546e-260, 6.01355013e-154, 3.54000724e-062,
        3.50669712e-033, 1.03278300e-047, 1.35888042e-153,
        1.69299977e-052, 8.15052254e-043, 1.58687178e-047,
        1.03345067e-047],
       [1.65488217e-153, 9.73711752e-072, 6.74195429e-067,
        6.22669418e-038, 6.22436687e-038, 2.48882177e-091,
        1.58687180e-047, 7.70210591e-043, 1.14460514e-071,
        2.21134729e-052],
       [2.48523325e-091, 2.00417370e-052, 3.65800218e-086,
        2.00417370e-052, 3.50668240e-033, 5.98154816e-154,
        4.01397422e-057, 4.66020281e-086, 4.08072630e-033,
        6.04414100e-154],
       [2.47379808e-091, 3.50669712e-033, 8.54516547e-072,
        1.48123091e-259, 2.00392185e-076, 6.01358422e-154,
        8.98353468e-067, 4.43687444e-038, 1.50833175e-153,
        7.1

# 2. Indexing Arrays <a id="s2"></a>

Similar to built-in data structures (e.g., `list`, `tuple`), an `ndarray` has indexes to indicate the location of each element.

Consider for example the following array: $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$

<br>

<center><figure>
  <img src="https://docs.google.com/drawings/d/e/2PACX-1vSpHjTf3tUlTWKDpaCfoUcVC_O59_Q2LJfFW4tpHku465W1BLrUfHPyAJ0J2_0ZbQHXpzlpfmA0GJHB/pub?w=446&h=134
" style="width:30%">
    <figcaption style="text-align:center"><strong> <br> Indexing elements in a 1-D NumPy array</strong></figcaption>   
</figure></center>

The concept of indexing in NumPy arrays is consistent with that of other data structures in Python, both for positive and negative indexing.

## 2.1. Single Element Indexing

In Python, we can access any value of a NumPy array using square brackets and the index of the desired element: `array_name[index]`

Let's use $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Get the first and second elements of <code>x</code> and add them. Repeat this using negative indexing.</div> 

In [43]:
# using positive indexing
print(x[0] + x[1])

# using negative indexing
print(x[-4] + x[-3])

2
2


For 2-D arrays, indexing is slightly different, since we have rows and columns. To index a 2-D array, we need to indicate the index of the row and the column, separated by a comma, using: `array_name[row_index, column_index]`. Think of 2-D arrays like a table with rows and columns, as shown in the illustration below. If you only think about the row index or the column index, then it is similar to a 1-D array. Negative indexing also works with 2-D arrays, similar to 1-D arrays.

<br>

<center><figure>
  <img src="https://docs.google.com/drawings/d/e/2PACX-1vSJpIGPqprNzpn7yNRyUR0rKEgBWtzVLcnp6Xs9T-9wRup9RNO7-D-uOQe7NRrWTYKxZSZqLTjEEnq5/pub?w=928&h=323
" style="width:70%">
    <figcaption style="text-align:center"><strong>Indexing elements in a 2-D NumPy array</strong></figcaption>   
</figure></center>

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Using negative indexing, get the element at the last row and last column of <code>y</code>.</div> 

In [45]:
y[-1, -1]

7

## 2.2. Slicing

We can also access a sequence of elements from a NumPy array using slicing, similar to other data structures.

In general, the syntax for slicing in Python is `array_name[start:end:step]`, where:
* `start`: an integer specifying the starting index (included). If `start` is not specified, slicing will start from index 0 (first position).
* `end`: an integer specifying the ending index (excluded). If `end` is not specified, slicing will end at the last index.
* `step`: an integer specifying the step between the indexes. If `step` is not specified, the result will be equivalent to using `step = 1`. If `step` is specified, the result will be elements with the following indexes: 

$$[\text{start, start + step, start + 2 $\times$ step, ...}]$$

When slicing in Python, the **upper-bound is exclusive**, which means that `array_name[1:3]` actually takes a slice from indexes 1 $\rightarrow$ 2 instead of 1 $\rightarrow$ 3. 

Let's use $w = \begin{pmatrix}0 & 1 & 2 & 3 & 4 & 5 & ... & 98 & 99 & 100\\\end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Run the code below and change the values for start, end, and step to check how they affect slicing.</div> 

In [47]:
import ipywidgets as widgets  # import ipywidgets package for interactive widgets

# create array w
w = np.arange(0, 101, 1)

# create 3 sliders for start, end, and step
@widgets.interact(start=(0,101), end=(0,101), step=(1,10))

# define a function that takes the values from the sliders and slices w
def slicing(start, end, step):
    print(f'\n >>> w[{start}:{end}:{step}] \n')
    print(w[start:end:step])
    return

interactive(children=(IntSlider(value=50, description='start', max=101), IntSlider(value=50, description='end'…

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Check the outputs of <code>w[:10]</code>, <code>w[:]</code>, and <code>w[::2]</code>.</div> 

In [49]:
# elements from index 0 (included) to 10 (excluded, so index 9, which is 10-1)
print(w[:10]) 

# the whole array, equivalent to [0:101:1] in this case
print(w[:]) 

# every other element starting from the beginning, equivalent to [0:101:2] in this case
print(w[::2]) 

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


You can also use negative indexes when slicing, similar to lists and tuples.

Let's use $w = \begin{pmatrix}0 & 1 & 2 & 3 & 4 & 5 & ... & 98 & 99 & 100\\\end{pmatrix}$ as an example.

```python
In [2]: w[:-1]
Out[2]: [ 0  1 2 3 4 ... 99]       
```

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Run the code below and change the values for start, end, and step to check how they affect slicing.</div> 

In [51]:
import ipywidgets as widgets  # import ipywidgets package for interactive widgets

# create array w
w = np.arange(0, 101, 1)

# create 3 sliders for start, end, and step
@widgets.interact(start=(-102,-1), end=(-102,-1), step=(-10,2))

# define a function that takes the values from the sliders and slices w
def slicing(start, end, step):
    print(f'\n >>> w[{start}:{end}:{step}] \n')
    print(w[start:end:step])
    return

interactive(children=(IntSlider(value=-52, description='start', max=-1, min=-102), IntSlider(value=-52, descri…

Slicing also works with 2-D arrays. If you only think about the row slicing or the column slicing, then each is similar to a 1-D array.

The general syntax for slicing a 2-D array is `array_name[start_row:end_row:step_row, start_col:end_col:step_col]`, where:
* `start_row`: The starting index for rows (inclusive).
* `end_row`: The ending index for rows (exclusive).
* `step_row`: The step size for rows.
* `start_col`: The starting index for columns (inclusive).
* `end_col`: The ending index for columns (exclusive).
* `step_col`: The step size for columns.

If `start`, `end`, or `step` are not specified, they default to 0, the size of the dimension, and 1, respectively.

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Get the first and third columns of <code>y</code>.</div> 

In [59]:
y[:, ::2]

array([[1, 3],
       [9, 7]])

## 2.3. Mutating an Array

NumPy arrays are **mutable**, which means that their contents **can** be modified.

You can use single element indexing and the assignment operator to modify a value of an array. You can also reassign multiple elements of an array to a single value using slicing, or alternatively, to multiple values as long as both the shape of the elements being assigned and the shape of the elements assigned are the same.  

**Examples:**

```python
>>> array = np.arange(1,6)
>>> print(array)

[1 2 3 4 5]

>>> array[1] = 10              # single element modification
>>> print(array)

[ 1 10  3  4  5]

>>> array[1:3] = 10            # multiple element modification to a single element
>>> print(array)

[ 1 10 10  4  5]

>>> array[1:3] = [-1, 0]       # multiple element modification to multiple elements
>>> print(array)

[ 1 -1  0  4  5]
```

Let's use $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Reassign the second element of <code>x</code> to 25.<br> &emsp;&emsp;&emsp;&ensp; Reassign the first and second elements of <code>x</code> to 19.<br> &emsp;&emsp;&emsp;&ensp; Reassign the second and fourth elements of <code>x</code> to 5 and 7, respectively.</div> 

In [65]:
x = np.array([-2, 4, 3, 12])

# reassign a single element to a single value
x[1] = 25
print(x)

# reassign multiple elements to a single value
x[:2] = 19
print(x)

# reassign multiple elements to a multiple values
x[1::2] = [5, 7]
print(x)

[-2 25  3 12]
[19 19  3 12]
[19  5  3  7]


# 3. Manipulating Arrays <a id="s3"></a>

Although reassigning values of an array can be helpful, this cannot be used to grow the array (i.e., add a new element to the array). NumPy provides several functions that can be used to manipulate arrays efficiently. 

## 3.1. Adding and Removing Elements

There are different functions that can be used to add or remove elements from an array, including:

* [`np.append(array, values)`](https://numpy.org/doc/stable/reference/generated/numpy.append.html#numpy.append): Append `values` to the end of `array`, where `values` can be a single value or array-like.

* [`np.insert(array, ind, values)`](https://numpy.org/doc/stable/reference/generated/numpy.insert.html#numpy.insert): Insert `values` into `array` before index(es) `ind`. Both `values` and `ind` can be a single value or array-like.

* [`np.delete(array, ind)`](https://numpy.org/doc/stable/reference/generated/numpy.delete.html#numpy.delete): Delete element(s) from `array` with index(es) `ind`, which can be a single value or array-like.

* [`np.unique(array)`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html#numpy.unique): Find the unique elements of `array` and return them in sorted order.

<div class="alert alert-block alert-warning"> <b>NOTE!</b> These functions will not automatically change the array. To change the array, you have to reassign it: <code>array = np.append(array, values)</code>.</div>

| `input`      | Function                   |  Output            |
| :----------: | :------------------------- | :----------------- |
| 😎😂🤩😎🤔 | `np.append(input, 🎉)`    | 😎😂🤩😎🤔🎉    |
| 😎😂🤩😎🤔 | `np.insert(input, 1, 🎉)` | 😎🎉😂🤩😎🤔    |
| 😎😂🤩😎🤔 | `np.delete(input, 1)`     | 😎🤩😎🤔         |
| 😎😂🤩😎🤔 | `np.unique(input)`        | 😎😂🤩🤔         |

Let's use $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Append the value 1 to the end of <code>x</code>.<br> &emsp;&emsp;&emsp;&ensp; Insert the values 8 and 9 before the first element of <code>x</code>.</div> 

In [ ]:
x = np.array([-2, 4, 3, 12])

# append
print(...)

# insert
print(...)

# x remains unchanged
print(x)

## 3.2. Concatenating and Splitting Arrays

In addition to manipulating single arrays, NumPy also provides functions to combine multiple arrays into one and to split a single array into multiple arrays. Some of these functions include:

* [`np.concatenate((array1, array2,...))`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate): Concatenate (join) two or more arrays of the same shape.

* [`np.split(array, ind_or_sections)`](https://numpy.org/doc/stable/reference/generated/numpy.split.html#numpy.split): Split `array` into multiple sub-arrays. If `ind_or_sections` is an integer, N, the array will be divided into N equal arrays along axis. If `ind_or_sections` is a 1-D array of sorted integers, the entries indicate the indexes at which the split will be performed.

<br>

<center><figure>
  <img src="https://docs.google.com/drawings/d/1I4O9hdVlt2xGRmrCsFtFsMNM7QYtO6QuDJZ87CTRBDc/pub?w=1440&h=1080" style="width:75%">
    <figcaption style="text-align:center"><strong> <br> Concatenate examples</strong></figcaption>   
</figure></center>

<br>

***

<br>

<center><figure>
  <img src="https://docs.google.com/drawings/d/1WTiwIO8lGrKc2J3zwlOqaIQ5qPBs138QYQCF2hUNK58/pub?w=1440&h=1080" style="width:70%">
    <figcaption style="text-align:center"><strong> <br> Split examples</strong></figcaption>   
</figure></center>

<br>

Let's use $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$ and $v = \begin{pmatrix}  13 & 4 & 5 & 2\\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Concatenate <code>x</code> and <code>v</code>.<br> &emsp;&emsp;&emsp;&ensp; Split <code>x</code> into two sub-arrays.</div> 

In [ ]:
x = np.array([-2, 4, 3, 12])
v = np.array([13, 4, 5, 2])

# concatenate

# split


There are other functions in NumPy for manipulating arrays. You can read about them in the [official documentation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html#array-manipulation-routines).

# 4. Array Methods <a id="s4"></a>

NumPy arrays have many methods, which manipulate its data or perform actions on an array. Some of the common methods are:
* [`array_name.cumsum()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.cumsum.html#numpy.ndarray.cumsum): returns the cumulative sum of the array elements along the given axis
* [`array_name.max()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html): returns the maximum of the array elements along the given axis
* [`array_name.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.mean.html): returns the average of the array elements along the given axis
* [`array_name.min()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html#numpy.ndarray.min): returns the minimum of the array elements along the given axis
* [`array_name.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html): sorts the array elements
* [`array_name.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html): returns the sum of the array elements along the given axis

There are other methods in NumPy for manipulating and performing actions on arrays. You can read about them in the [official documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

Let's use $x = \begin{pmatrix}  -2 & 4 & 3 & 12\\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Get the mean of <code>x</code>.<br> &emsp;&emsp;&emsp;&ensp; Get the sum of <code>x</code>.</div> 

In [69]:
x = np.array([-2, 4, 3, 12])

# mean
x.mean()
# sum
x.sum()

17

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Notice that we used <code>x.sum()</code> instead of <code>x.sum</code>. This is because <code>sum</code> is a <strong>method</strong>, which is a function associated with an object. For now you need to remember that when we call a method on an object, we need to use parentheses. You can always try both and see which works!</div>

# 5. Arithmetic and Comparison Operations <a id="s5"></a>

Some of the arithmetic and comparison operators we have used on scalar objects can also be used on arrays. These arithmetic and comparison operations behave differently compared to Python lists or tuples.

## 5.1. Arithmetic Operations

Basic arithmetic is defined for arrays. However, there are operations between a scalar (a single number) and an array and operations between two arrays. We will start with operations between a scalar and an array. To illustrate, let $c$ be a scalar, and $A$ be an array.

* `A + c`: adds $c$ to every element of $A$ 
* `A − c`: subtracts $c$ from every element of $A$
* `A * c`: multiplies every element of $A$ by $c$
* `A / c`: divides every element of $A$ by $c$
* `A ** c`: raises every element of $A$ to the power $c$

These apply to 1-D and 2-D arrays.

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Square the values of <code>y</code>.</div> 

In [73]:
# y squared
print(y ** 2)
# y remains unchanged
print(y)

[[ 1 16  9]
 [81  4 49]]
[[1 4 3]
 [9 2 7]]


<div class="alert alert-block alert-warning"> <b>NOTE!</b> We did not reassign <code>y</code> when doing the above operation (we did not, for example, use <code>y = y ** 2</code>). Therefore, <code>y</code> remains unchanged.</div>

We can also perform operations between two or more arrays. Let $A1$ and $A2$ be two arrays of the **same shape**.
* `A1 + A2`: takes every element of $A1$ and add it to the corresponding element of $A2$ in the same index
* `A1 - A2`: takes every element of $A2$ and subtracts it from the corresponding element of $A1$ in the same index
* `A1 * A2`: takes every element of $A1$ and multiplies it by the corresponding element of $A2$ in the same index
* `A1 / A2`: takes every element of $A1$ and divides it by the corresponding element of $A2$ in the same index
* `A1 ** A2`: takes every element of $A1$ and raises it to the power the corresponding element of $A2$ in the same index

<div class="alert alert-block alert-warning"> <b>NOTE!</b> If you have taken linear algebra, you will notice that <code>A1 * A2</code> is different from that standard array multiplication. Standard array multiplication will be described in a later chapter. The operations above are known as element-by-element operations.</div>

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ and $z = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Perform element-by-element multiplication between <code>y</code> and <code>z</code>.</div> 

In [75]:
y = np.array([[1, 4, 3], [9, 2, 7]])
z = np.array([[1, 2, 3], [4, 5, 6]])

# element-by-element multiplication
y * z

array([[ 1,  8,  9],
       [36, 10, 42]])

NumPy has many mathematical functions, such as `np.sin()`, `np.cos()`, etc., that can take arrays as input arguments. The output is an array that includes the outputs of the function evaluated for every element of the input array. A list of mathematical funcitons in NumPy can be found in the [official documentation](https://numpy.org/doc/stable/reference/routines.math.html).

<div class="alert alert-block alert-warning"> <b>NOTE!</b> While many of these functions are similar to those available in the <code>math</code> module, you cannot use the functions from <code>math</code> directly on NumPy arrays. Instead, you should use the equivalent functions available in the NumPy module.</div>

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Compute the square root of <code>y</code> using <code>np.sqrt()</code>.</div> 

In [77]:
np.sqrt(y)

array([[1.        , 2.        , 1.73205081],
       [3.        , 1.41421356, 2.64575131]])

## 5.2. Comparison Operations

Logical expressions can be applied to arrays in NumPy, allowing for comparisons between elements within arrays or between arrays and scalars.

### 5.2.1. Comparisons Between a Scalar and an Array

When comparing a scalar to an array, the comparison is performed between the scalar and **each element** of the array. The output will be an array of the same shape as the original array, containing `True` or `False` based on the result of the comparison.

### 5.2.2. Comparisons Between Two Arrays

When comparing two arrays of the **same shape**, the comparison is conducted element-wise (i.e., **element-by-element**). The output will be an array of the same shape as the original arrays, containing `True` or `False` based on the result of the comparison for each corresponding pair of elements.

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ and $z = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Check which elements of <code>y</code> are greater than 3. Check which elements of <code>y</code> are equal to the corresponding element of <code>z</code>.</div> 

In [81]:
# greater than 3
y > 3
# equal to z
y == z

array([[ True, False,  True],
       [False, False, False]])

### 5.2.3. Logical Operators

The standard logical operators `and` and `or` are not directly applicable to NumPy arrays. Attempting to use these operators directly with arrays will raise an error.

To perform element-wise logical AND and OR operations between two arrays, you should use NumPy's specialized logical functions:

* `np.logical_and(expression1, expression2)`: Performs element-wise logical AND operation between corresponding elements of `expression1` and `expression2`.
* `np.logical_or(expression1, expression2)`: Performs element-wise logical OR operation between corresponding elements of `expression1` and `expression2`.

### 5.2.4. Indexing Elements Based on Logical Expressions

Python allows indexing elements of an array based on logical expressions, which is particularly useful for extracting specific elements that satisfy certain conditions. Instead of giving the values of the indexes, a logical expression can be used directly to filter the elements of the array.

Let's use $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ \end{pmatrix}$ as an example.

<div class="alert alert-block alert-info"> <b>TRY IT!</b> Create a new array that contains all the elements of <code>y</code> that are strictly greater than 3.<br> &emsp;&emsp;&emsp;&ensp; Assign all the values of <code>y</code> that are greater than 3 the value 0.</div> 

In [ ]:
y = np.array([[1, 4, 3], [9, 2, 7]])

# new array

# indexing with logical expression

print(y)